//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gear.ShellCommands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShellResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShellResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gear.ShellCommands.ShellResources", typeof(ShellResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exits the game..
        /// </summary>
        internal static string ExitCommand_description {
            get {
                return ResourceManager.GetString("ExitCommand_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string ExitCommand_name {
            get {
                return ResourceManager.GetString("ExitCommand_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string ExitCommand_usage {
            get {
                return ResourceManager.GetString("ExitCommand_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays help for a command..
        /// </summary>
        internal static string HelpCommand_description {
            get {
                return ResourceManager.GetString("HelpCommand_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string HelpCommand_name {
            get {
                return ResourceManager.GetString("HelpCommand_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help [command].
        /// </summary>
        internal static string HelpCommand_usage {
            get {
                return ResourceManager.GetString("HelpCommand_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists available commands..
        /// </summary>
        internal static string ListCommand_description {
            get {
                return ResourceManager.GetString("ListCommand_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string ListCommand_name {
            get {
                return ResourceManager.GetString("ListCommand_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list [search_filter].
        /// </summary>
        internal static string ListCommand_usage {
            get {
                return ResourceManager.GetString("ListCommand_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a chat message to other players..
        /// </summary>
        internal static string SayCommand_description {
            get {
                return ResourceManager.GetString("SayCommand_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to say.
        /// </summary>
        internal static string SayCommand_name {
            get {
                return ResourceManager.GetString("SayCommand_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to say [#destination] &lt;message&gt;.
        /// </summary>
        internal static string SayCommand_usage {
            get {
                return ResourceManager.GetString("SayCommand_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets a runtime engine variable..
        /// </summary>
        internal static string SetCommand_description {
            get {
                return ResourceManager.GetString("SetCommand_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        internal static string SetCommand_name {
            get {
                return ResourceManager.GetString("SetCommand_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set &lt;variable&gt; [data].
        /// </summary>
        internal static string SetCommand_usage {
            get {
                return ResourceManager.GetString("SetCommand_usage", resourceCulture);
            }
        }
    }
}
